// import './components/context-router/context-router.ts'
import './components/context-media/context-media.ts'
import './components/hello-world/hello-world.ts'
import './components/basic-button/basic-button.ts'
import './components/basic-counter/basic-counter.ts'
import './components/basic-number/basic-number.ts'
import './components/basic-pluralize/basic-pluralize.ts'
import './components/form-checkbox/form-checkbox.ts'
import './components/form-radiogroup/form-radiogroup.ts'
import './components/form-textbox/form-textbox.ts'
import './components/form-combobox/form-combobox.ts'
import './components/form-spinbutton/form-spinbutton.ts'
import './components/module-carousel/module-carousel.ts'
import './components/module-catalog/module-catalog.ts'
import './components/module-codeblock/module-codeblock.ts'
import './components/module-tabgroup/module-tabgroup.ts'
import './components/module-lazy/module-lazy.ts'
import './components/module-todo/module-todo.ts'
import './components/rating-stars/rating-stars.ts'
import './components/rating-feedback/rating-feedback.ts'
import './components/calc-table/calc-table.ts'
// Import more custom elements here...
