import './components/hello-world/hello-world.ts'
import './components/my-counter/my-counter.ts'
import './components/my-slider/my-slider.ts'
import './components/input-button/input-button.ts'
import './components/input-checkbox/input-checkbox.ts'
import './components/input-radiogroup/input-radiogroup.ts'
import './components/input-field/input-field.ts'
import './components/code-block/code-block.ts'
import './components/tab-list/tab-list.ts'
import './components/accordion-panel/accordion-panel.ts'
import './components/lazy-load/lazy-load.ts'
import './components/media-context/media-context.ts'
import './components/todo-app/todo-app.ts'
import './components/product-catalog/product-catalog.ts'
import './components/spin-button/spin-button.ts'
// Import more custom elements here...